# frozen_string_literal: true
# This file is auto-generated by the release-cli workflow.
# Do not edit manually — changes will be overwritten on next release.

class Ass < Formula
  desc "CLI for Agent Secret Store — the secure vault built for AI agents"
  homepage "https://agentsecretstore.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Agent-Secret-Store/agent-secret-store/releases/download/v1.0.0/ass-macos-arm64"
      sha256 "04cba75810033d25f67d3d9491e9f6bb37047838650c875702d67538d6c46855"
    end

    on_intel do
      url "https://github.com/Agent-Secret-Store/agent-secret-store/releases/download/v1.0.0/ass-macos-x64"
      sha256 "86c48bae71bed489e046c3d8114d82f8274877b4c44413879128aa2bb91278af"
    end
  end

  on_linux do
    on_arm do
      # Linux arm64 not yet supported — raise an error
      odie "Linux arm64 binaries are not currently provided. Use npm: npm install -g @agentsecretstore/cli"
    end

    on_intel do
      url "https://github.com/Agent-Secret-Store/agent-secret-store/releases/download/v1.0.0/ass-linux-x64"
      sha256 "8e3d99003704b6ec2e52421780386402cd67ff7295f839e5ca7848a13f4a978c"
    end
  end

  def install
    bin.install Dir["ass*"].first => "ass"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ass --version")
  end
end
